CREATE TABLE COUNTRY (
COUNTRY_CODE NUMERIC(3) PRIMARY KEY,
COUNTRY_NAME VARCHAR(50) NOT NULL);

CREATE TABLE STADIUM (
STADIUM_CODE NUMERIC(2) PRIMARY KEY,
STADIUM_NAME VARCHAR(25) NOT NULL,
STADIUM_LOCATION VARCHAR(50) NOT NULL,
STADIUM_CAPACITY NUMERIC(6) NOT NULL);

CREATE TABLE REFEREE (
REFEREE_CODE NUMERIC(3) PRIMARY KEY,
REFEREE_LASTNAME VARCHAR(40) NOT NULL,
REFEREE_FIRSTNAME VARCHAR(40) NOT NULL,
REFEREE_DATEOFBIRTH DATE NOT NULL,
REFEREE_EXPERIENCE YEAR NOT NULL,
REFEREE_COUNTRY NUMERIC(3),
INDEX(REFEREE_COUNTRY),
CONSTRAINT FK_REFEREE_COUNTRY FOREIGN KEY(REFEREE_COUNTRY) REFERENCES COUNTRY(COUNTRY_CODE));

CREATE TABLE COACH (
COACH_CODE NUMERIC(3) PRIMARY KEY,
COACH_LASTNAME VARCHAR(40) NOT NULL,
COACH_FIRSTNAME VARCHAR(40) NOT NULL,
COACH_DATEOFBIRTH DATE NOT NULL,
COACH_COUNTRY NUMERIC(3),
INDEX(COACH_COUNTRY),
CONSTRAINT FK_COACH_COUNTRY FOREIGN KEY(COACH_COUNTRY) REFERENCES COUNTRY(COUNTRY_CODE));

CREATE TABLE TEAM (
TEAM_CODE NUMERIC(3) PRIMARY KEY,
TEAM_COUNTRY NUMERIC(3),
TEAM_COACH NUMERIC(3),
TEAM_NUMBERMATCHPLAYED NUMERIC(1) NOT NULL,
TEAM_NUMBERMATCHWON NUMERIC(1) NOT NULL,
TEAM_NUMBERMATCHLOST NUMERIC(1) NOT NULL,
TEAM_NUMBERMATCHDRAW NUMERIC(1) NOT NULL,
TEAM_GOALSFOR NUMERIC(2) NOT NULL,
TEAM_GOALSAGAINST NUMERIC(2) NOT NULL,
TEAM_POINTS NUMERIC(2) NOT NULL,
TEAM_POSITION NUMERIC(3) NOT NULL,
TEAM_GROUP CHAR(1) NOT NULL,
INDEX(TEAM_COUNTRY),
INDEX(TEAM_COACH),
CONSTRAINT FK_TEAM_COUNTRY FOREIGN KEY (TEAM_COUNTRY) REFERENCES COUNTRY(COUNTRY_CODE),
CONSTRAINT FK_TEAM_COACH FOREIGN KEY (TEAM_COACH) REFERENCES COACH(COACH_CODE));

CREATE TABLE PLAYER (
PLAYER_CODE NUMERIC(4) PRIMARY KEY,
PLAYER_LASTNAME VARCHAR(40) NOT NULL,
PLAYER_FIRSTNAME VARCHAR(40) NOT NULL,
PLAYER_BIRTHDATE DATE NOT NULL,
PLAYER_TEAM NUMERIC(3),
PLAYER_POSITION ENUM('goalkeeper','defender','midfielder','forward') NOT NULL,
PLAYER_CURRENTCLUB VARCHAR(25) NOT NULL,
PLAYER_HEIGHT NUMERIC(3) NOT NULL,
PLAYER_SHIRTNUMBER NUMERIC(2) NOT NULL,
INDEX(PLAYER_TEAM),
CONSTRAINT FK_PLAYER_TEAM FOREIGN KEY (PLAYER_TEAM) REFERENCES TEAM(TEAM_CODE));

CREATE TABLE GAME (
GAME_CODE NUMERIC(3) PRIMARY KEY,
GAME_KIND ENUM('groupstage','roundof16','quarterfinals','semifinals','final') NOT NULL,
GAME_WINNERTEAM NUMERIC(3),
GAME_LOSSTEAM NUMERIC(3),
GAME_TIME TIME NOT NULL,
GAME_DATE DATE NOT NULL,
GAME_WINNERTEAMSCORE NUMERIC(2) NOT NULL,
GAME_LOSSTEAMSCORE NUMERIC(2) NOT NULL,
GAME_REFEREE NUMERIC(3),
GAME_REFASIST1 NUMERIC(3),
GAME_REFASIST2 NUMERIC(3),
GAME_REF4TH NUMERIC(3),
GAME_REFASISTSUP NUMERIC(3),
GAME_STADIUM NUMERIC(2),
INDEX(GAME_WINNERTEAM),
INDEX(GAME_LOSSTEAM),
INDEX(GAME_REFEREE),
INDEX(GAME_REFASIST1),
INDEX(GAME_REFASIST2),
INDEX(GAME_REF4TH),
INDEX(GAME_REFASISTSUP),
INDEX(GAME_STADIUM),
CONSTRAINT FK_GAME_WINNERTEAM FOREIGN KEY (GAME_WINNERTEAM) REFERENCES TEAM(TEAM_CODE),
CONSTRAINT FK_GAME_LOSSTEAM FOREIGN KEY (GAME_LOSSTEAM) REFERENCES TEAM(TEAM_CODE),
CONSTRAINT FK_GAME_REFEREEE FOREIGN KEY (GAME_REFEREE) REFERENCES REFEREE(REFEREE_CODE),
CONSTRAINT FK_GAME_REFASIST1 FOREIGN KEY (GAME_REFASIST1) REFERENCES REFEREE(REFEREE_CODE),
CONSTRAINT FK_GAME_REFASIST2 FOREIGN KEY (GAME_REFASIST2) REFERENCES REFEREE(REFEREE_CODE),
CONSTRAINT FK_GAME_REF4TH FOREIGN KEY (GAME_REF4TH) REFERENCES REFEREE(REFEREE_CODE),
CONSTRAINT FK_GAME_REFASISTSUP FOREIGN KEY (GAME_REFASISTSUP) REFERENCES REFEREE(REFEREE_CODE),
CONSTRAINT FK_GAME_STADIUM FOREIGN KEY (GAME_STADIUM) REFERENCES STADIUM(STADIUM_CODE));

CREATE TABLE GOAL (
GOAL_CODE NUMERIC(3) PRIMARY KEY,
GOAL_GAME NUMERIC(3),
GOAL_PLAYER NUMERIC(4),
GOAL_TIME TIME NOT NULL,
INDEX(GOAL_GAME),
INDEX(GOAL_PLAYER),
CONSTRAINT FK_GOAL_GAME FOREIGN KEY (GOAL_GAME) REFERENCES GAME(GAME_CODE),
CONSTRAINT FK_GOAL_PLAYER FOREIGN KEY (GOAL_PLAYER) REFERENCES PLAYER(PLAYER_CODE));

ALTER TABLE TEAM
ADD TEAM_CAPTAIN NUMERIC(4),
ADD INDEX(TEAM_CAPTAIN),
ADD CONSTRAINT FK_TEAM_CAPTAIN FOREIGN KEY (TEAM_CAPTAIN) REFERENCES PLAYER(PLAYER_CODE);