SELECT * FROM PLAYER WHERE PLAYER_TEAM = (
SELECT TEAM_CODE FROM TEAM WHERE TEAM_COUNTRY = (
SELECT COUNTRY_CODE FROM COUNTRY WHERE COUNTRY_NAME = 'Germany'))
ORDER BY PLAYER_LASTNAME;

SELECT TEAM_POSITION AS POSITION,COUNTRY_NAME AS COUNTRY, CONCAT(UPPER(COACH_LASTNAME),LOWER(COACH_FIRSTNAME)) AS COACH, TEAM_GROUP
FROM COUNTRY,TEAM,COACH
WHERE TEAM_COUNTRY=COUNTRY_CODE AND TEAM_COACH=COACH_CODE
ORDER BY TEAM_POSITION;

SELECT DISTINCT REFEREE_COUNTRY, COUNTRY_NAME
FROM REFEREE,COUNTRY
WHERE REFEREE_COUNTRY = COUNTRY_CODE;

SELECT COUNT(*)
FROM GOAL
WHERE GOAL_PLAYER=038;

CREATE VIEW GOALSMARKED AS
SELECT PLAYER_CODE, PLAYER_LASTNAME, PLAYER_FIRSTNAME, GOAL_CODE, GOAL_TIME
FROM PLAYER,GOAL
WHERE PLAYER_CODE=GOAL_PLAYER;

CREATE VIEW NUMBEROFGOALS AS
SELECT PLAYER_LASTNAME, PLAYER_FIRSTNAME,COUNT(PLAYER_CODE) AS NUMBEROFGOALSMARKED
FROM GOALSMARKED
GROUP BY PLAYER_CODE
ORDER BY NUMBEROFGOALSMARKED;

SELECT *
FROM STADIUM
WHERE STADIUM_CAPACITY>60000;

SELECT GAME_CODE,GAME_KIND,GAME_WINNERTEAM AS WINNER,GAME_LOSSTEAM AS LOSER,GAME_TIME,GAME_DATE 
FROM  GAME
WHERE GAME_KIND IN ('quarterfinals','semifinals');

SELECT STADIUM_NAME,STADIUM_LOCATION, STADIUM_CAPACITY 
FROM  STADIUM
WHERE STADIUM_LOCATION LIKE ('J%');

SELECT  PLAYER_CODE, PLAYER_LASTNAME, PLAYER_FIRSTNAME, PLAYER_HEIGHT 
FROM  PLAYER
GROUP BY  PLAYER_HEIGHT 
HAVING  PLAYER_HEIGHT<185;

SELECT  PLAYER_LASTNAME, PLAYER_LASTNAME, PLAYER_TEAM, FLOOR(DATEDIFF(CURRENT_DATE(),PLAYER_BIRTHDATE)/365) AS AGE, COUNTRY_NAME
FROM PLAYER,COUNTRY
WHERE PLAYER_TEAM = (
SELECT TEAM_CODE FROM TEAM
WHERE TEAM_COUNTRY=COUNTRY_CODE)
ORDER BY COUNTRY_NAME,AGE;